version: "3.2"
services:
  hospital-integration-tests:
      container_name: hospital-integration-tests
      build:
        dockerfile: stacks/build/hospital/test/Dockerfile
      ports:
        - "5000:8080"
      environment:
        DATABASE_HOST: database
        DATABASE_PORT: 5432
        DATABASE_SCHEMA: hospitalDb
        DATABASE_USER: postgres
        DATABASE_PASSWORD: password
      networks:
        - database_net
      depends_on:
        - database  
  database:
    image: postgres:latest
    restart: always
    container_name: database
    networks:
      - database_net
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "hospitalDb"
    ports:
      - "5433:5432"

networks:
  database_net:
    name: database_net
    driver: bridge 