version: "3.2"
services:
  hospital-api:
    image: nenadbecanovic/hospital-api:latest
    #image: hospitalapi
    #build:
    #  context: ../
    #  dockerfile: ../stacks/build/hospital/Dockerfile
    depends_on:
      - "database"
    ports:
      - "5000:8080"
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_SCHEMA: hospitalDb
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
    networks:
      - application
      - hospital-database
  
  database: 
    image: postgres:latest
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - type: volume
        source: hospital-data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./HealthCareClinic/Hospital API/database.sql 
        target: /docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "hospitalDb"
    networks:
      - hospital-database
    
  hospital-integration-tests:
    container_name: hospital-integration-tests
    image: mcr.microsoft.com/dotnet/sdk:5.0
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_SCHEMA: hospitalDb
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
    working_dir: /Scripts
    command:
      [
        "./wait-for-it.sh",
        "database:5432",
        "--",
        "dotnet",
        "test",
        "HealthCareClinic/HospitalIntegrationTests/HospitalIntegrationTests.csproj"
      ]
    depends_on:
      - database
volumes:
  hospital-data:

networks:
  application:
    driver: bridge
  hospital-database:
    driver: bridge