// <auto-generated />
using System;
using Hospital.Mapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Hospital.Migrations
{
    [DbContext(typeof(HospitalDbContext))]
    [Migration("20211116221737_FourthMigrationGraphicalEditor")]
    partial class FourthMigrationGraphicalEditor
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("ClinicCore.Model.FeedbackMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("CanBePublished")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Identity")
                        .HasColumnType("text");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FeedbackMessages");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CanBePublished = true,
                            Date = new DateTime(2021, 4, 29, 18, 34, 21, 0, DateTimeKind.Unspecified),
                            Identity = "acaNikolic",
                            IsAnonymous = false,
                            IsPublished = false,
                            Text = "Zadovoljan sam uslugom."
                        },
                        new
                        {
                            Id = 2L,
                            CanBePublished = true,
                            Date = new DateTime(2021, 6, 21, 14, 21, 56, 0, DateTimeKind.Unspecified),
                            Identity = "NikolaTodorovic94",
                            IsAnonymous = true,
                            IsPublished = false,
                            Text = "Čekanje je moglo biti kraće."
                        },
                        new
                        {
                            Id = 3L,
                            CanBePublished = false,
                            Date = new DateTime(2021, 2, 16, 11, 8, 47, 0, DateTimeKind.Unspecified),
                            Identity = "MarijaPopovic",
                            IsAnonymous = false,
                            IsPublished = false,
                            Text = "Informacionom sistemu potrebne su određene popravke."
                        },
                        new
                        {
                            Id = 4L,
                            CanBePublished = true,
                            Date = new DateTime(2021, 5, 20, 9, 10, 21, 0, DateTimeKind.Unspecified),
                            Identity = "UrosDevic0",
                            IsAnonymous = false,
                            IsPublished = false,
                            Text = "Odlični lekari."
                        },
                        new
                        {
                            Id = 5L,
                            CanBePublished = true,
                            Date = new DateTime(2021, 9, 30, 7, 50, 19, 0, DateTimeKind.Unspecified),
                            Identity = "MladenAlicic1",
                            IsAnonymous = false,
                            IsPublished = true,
                            Text = "Savremena bolnica koju bih preporučio ljudima."
                        },
                        new
                        {
                            Id = 6L,
                            CanBePublished = true,
                            Date = new DateTime(2021, 9, 30, 7, 50, 19, 0, DateTimeKind.Unspecified),
                            Identity = "IvanJovanovic",
                            IsAnonymous = false,
                            IsPublished = true,
                            Text = "Savremena bolnica koju bih preporučio ljudima."
                        },
                        new
                        {
                            Id = 7L,
                            CanBePublished = true,
                            Date = new DateTime(2021, 9, 30, 7, 50, 19, 0, DateTimeKind.Unspecified),
                            Identity = "JovanaGugl",
                            IsAnonymous = false,
                            IsPublished = true,
                            Text = "Savremena bolnica koju bih preporučio ljudima."
                        },
                        new
                        {
                            Id = 8L,
                            CanBePublished = true,
                            Date = new DateTime(2021, 9, 30, 7, 50, 19, 0, DateTimeKind.Unspecified),
                            Identity = "RatkoVarda8",
                            IsAnonymous = false,
                            IsPublished = true,
                            Text = "Savremena bolnica koju bih preporučio ljudima."
                        });
                });

            modelBuilder.Entity("Hospital.Rooms_and_equipment.Model.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<float>("Width")
                        .HasColumnType("real");

                    b.Property<float>("X")
                        .HasColumnType("real");

                    b.Property<float>("Y")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Height = 140f,
                            Name = "Building1",
                            Type = 0,
                            Width = 400f,
                            X = 260f,
                            Y = 30f
                        },
                        new
                        {
                            Id = 2,
                            Height = 140f,
                            Name = "Building2",
                            Type = 0,
                            Width = 400f,
                            X = 260f,
                            Y = 230f
                        },
                        new
                        {
                            Id = 3,
                            Height = 240f,
                            Name = "Building3",
                            Type = 0,
                            Width = 180f,
                            X = 30f,
                            Y = 130f
                        },
                        new
                        {
                            Id = 4,
                            Height = 140f,
                            Name = "Building4",
                            Type = 0,
                            Width = 300f,
                            X = 700f,
                            Y = 230f
                        },
                        new
                        {
                            Id = 5,
                            Height = 70f,
                            Name = "Parking1",
                            Type = 1,
                            Width = 200f,
                            X = 30f,
                            Y = 30f
                        },
                        new
                        {
                            Id = 6,
                            Height = 70f,
                            Name = "Parking2",
                            Type = 1,
                            Width = 200f,
                            X = 800f,
                            Y = 30f
                        },
                        new
                        {
                            Id = 7,
                            Height = 70f,
                            Name = "Parking3",
                            Type = 1,
                            Width = 200f,
                            X = 800f,
                            Y = 130f
                        });
                });

            modelBuilder.Entity("Hospital.Rooms_and_equipment.Model.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bed",
                            Quantity = 5,
                            RoomId = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Needle",
                            Quantity = 25,
                            RoomId = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "TV",
                            Quantity = 1,
                            RoomId = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bandage",
                            Quantity = 10,
                            RoomId = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Blanket",
                            Quantity = 5,
                            RoomId = 1,
                            Type = 0
                        });
                });

            modelBuilder.Entity("Hospital.Rooms_and_equipment.Model.Floor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("BuildingId")
                        .HasColumnType("integer");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<float>("Width")
                        .HasColumnType("real");

                    b.Property<float>("X")
                        .HasColumnType("real");

                    b.Property<float>("Y")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Floors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuildingId = 1,
                            Height = 0f,
                            Name = "Floor 1",
                            Width = 0f,
                            X = 0f,
                            Y = 0f
                        },
                        new
                        {
                            Id = 2,
                            BuildingId = 1,
                            Height = 0f,
                            Name = "Floor 2",
                            Width = 0f,
                            X = 0f,
                            Y = 0f
                        },
                        new
                        {
                            Id = 3,
                            BuildingId = 1,
                            Height = 0f,
                            Name = "Floor 3",
                            Width = 0f,
                            X = 0f,
                            Y = 0f
                        },
                        new
                        {
                            Id = 4,
                            BuildingId = 2,
                            Height = 0f,
                            Name = "Floor 1",
                            Width = 0f,
                            X = 0f,
                            Y = 0f
                        },
                        new
                        {
                            Id = 5,
                            BuildingId = 2,
                            Height = 0f,
                            Name = "Floor 2",
                            Width = 0f,
                            X = 0f,
                            Y = 0f
                        },
                        new
                        {
                            Id = 6,
                            BuildingId = 3,
                            Height = 0f,
                            Name = "Floor 1",
                            Width = 0f,
                            X = 0f,
                            Y = 0f
                        },
                        new
                        {
                            Id = 7,
                            BuildingId = 3,
                            Height = 0f,
                            Name = "Floor 2",
                            Width = 0f,
                            X = 0f,
                            Y = 0f
                        },
                        new
                        {
                            Id = 8,
                            BuildingId = 3,
                            Height = 0f,
                            Name = "Floor 3",
                            Width = 0f,
                            X = 0f,
                            Y = 0f
                        },
                        new
                        {
                            Id = 9,
                            BuildingId = 4,
                            Height = 0f,
                            Name = "Floor 1",
                            Width = 0f,
                            X = 0f,
                            Y = 0f
                        },
                        new
                        {
                            Id = 10,
                            BuildingId = 4,
                            Height = 0f,
                            Name = "Floor 2",
                            Width = 0f,
                            X = 0f,
                            Y = 0f
                        });
                });

            modelBuilder.Entity("Hospital.Rooms_and_equipment.Model.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("FloorId")
                        .HasColumnType("integer");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<float>("Width")
                        .HasColumnType("real");

                    b.Property<float>("X")
                        .HasColumnType("real");

                    b.Property<float>("Y")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Room description...",
                            FloorId = 1,
                            Height = 140f,
                            Name = "Operation room",
                            Type = 1,
                            Width = 400f,
                            X = 320f,
                            Y = 30f
                        },
                        new
                        {
                            Id = 2,
                            Description = "Room description...",
                            FloorId = 1,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 380f,
                            X = 320f,
                            Y = 260f
                        },
                        new
                        {
                            Id = 3,
                            Description = "Room description...",
                            FloorId = 1,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 270f,
                            X = 50f,
                            Y = 260f
                        },
                        new
                        {
                            Id = 4,
                            Description = "Room description...",
                            FloorId = 1,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 300f,
                            X = 700f,
                            Y = 260f
                        },
                        new
                        {
                            Id = 5,
                            Description = "Room description...",
                            FloorId = 1,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 270f,
                            X = 50f,
                            Y = 30f
                        },
                        new
                        {
                            Id = 6,
                            Description = "Room description...",
                            FloorId = 1,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 280f,
                            X = 720f,
                            Y = 30f
                        },
                        new
                        {
                            Id = 7,
                            Description = "Room description...",
                            FloorId = 1,
                            Height = 90f,
                            Name = "WC",
                            Type = 2,
                            Width = 150f,
                            X = 50f,
                            Y = 170f
                        },
                        new
                        {
                            Id = 8,
                            Description = "Room description...",
                            FloorId = 2,
                            Height = 140f,
                            Name = "Operation room",
                            Type = 1,
                            Width = 400f,
                            X = 320f,
                            Y = 30f
                        },
                        new
                        {
                            Id = 9,
                            Description = "Room description...",
                            FloorId = 2,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 380f,
                            X = 320f,
                            Y = 260f
                        },
                        new
                        {
                            Id = 10,
                            Description = "Room description...",
                            FloorId = 2,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 270f,
                            X = 50f,
                            Y = 260f
                        },
                        new
                        {
                            Id = 11,
                            Description = "Room description...",
                            FloorId = 2,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 300f,
                            X = 700f,
                            Y = 260f
                        },
                        new
                        {
                            Id = 12,
                            Description = "Room description...",
                            FloorId = 2,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 270f,
                            X = 50f,
                            Y = 30f
                        },
                        new
                        {
                            Id = 13,
                            Description = "Room description...",
                            FloorId = 2,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 280f,
                            X = 720f,
                            Y = 30f
                        },
                        new
                        {
                            Id = 14,
                            Description = "Room description...",
                            FloorId = 2,
                            Height = 90f,
                            Name = "WC",
                            Type = 2,
                            Width = 150f,
                            X = 50f,
                            Y = 170f
                        },
                        new
                        {
                            Id = 15,
                            Description = "Room description...",
                            FloorId = 3,
                            Height = 140f,
                            Name = "Operation room",
                            Type = 1,
                            Width = 400f,
                            X = 320f,
                            Y = 30f
                        },
                        new
                        {
                            Id = 16,
                            Description = "Room description...",
                            FloorId = 3,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 380f,
                            X = 320f,
                            Y = 260f
                        },
                        new
                        {
                            Id = 17,
                            Description = "Room description...",
                            FloorId = 3,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 270f,
                            X = 50f,
                            Y = 260f
                        },
                        new
                        {
                            Id = 18,
                            Description = "Room description...",
                            FloorId = 3,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 300f,
                            X = 700f,
                            Y = 260f
                        },
                        new
                        {
                            Id = 19,
                            Description = "Room description...",
                            FloorId = 3,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 270f,
                            X = 50f,
                            Y = 30f
                        },
                        new
                        {
                            Id = 20,
                            Description = "Room description...",
                            FloorId = 3,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 280f,
                            X = 720f,
                            Y = 30f
                        },
                        new
                        {
                            Id = 21,
                            Description = "Room description...",
                            FloorId = 3,
                            Height = 90f,
                            Name = "WC",
                            Type = 2,
                            Width = 150f,
                            X = 50f,
                            Y = 170f
                        },
                        new
                        {
                            Id = 22,
                            Description = "Room description...",
                            FloorId = 4,
                            Height = 140f,
                            Name = "Operation room",
                            Type = 1,
                            Width = 400f,
                            X = 320f,
                            Y = 30f
                        },
                        new
                        {
                            Id = 23,
                            Description = "Room description...",
                            FloorId = 4,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 380f,
                            X = 320f,
                            Y = 260f
                        },
                        new
                        {
                            Id = 24,
                            Description = "Room description...",
                            FloorId = 4,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 270f,
                            X = 50f,
                            Y = 260f
                        },
                        new
                        {
                            Id = 25,
                            Description = "Room description...",
                            FloorId = 4,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 300f,
                            X = 700f,
                            Y = 260f
                        },
                        new
                        {
                            Id = 26,
                            Description = "Room description...",
                            FloorId = 4,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 270f,
                            X = 50f,
                            Y = 30f
                        },
                        new
                        {
                            Id = 27,
                            Description = "Room description...",
                            FloorId = 4,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 280f,
                            X = 720f,
                            Y = 30f
                        },
                        new
                        {
                            Id = 28,
                            Description = "Room description...",
                            FloorId = 4,
                            Height = 90f,
                            Name = "WC",
                            Type = 2,
                            Width = 150f,
                            X = 50f,
                            Y = 170f
                        },
                        new
                        {
                            Id = 29,
                            Description = "Room description...",
                            FloorId = 5,
                            Height = 140f,
                            Name = "Operation room",
                            Type = 1,
                            Width = 400f,
                            X = 320f,
                            Y = 30f
                        },
                        new
                        {
                            Id = 30,
                            Description = "Room description...",
                            FloorId = 5,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 380f,
                            X = 320f,
                            Y = 260f
                        },
                        new
                        {
                            Id = 31,
                            Description = "Room description...",
                            FloorId = 5,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 270f,
                            X = 50f,
                            Y = 260f
                        },
                        new
                        {
                            Id = 32,
                            Description = "Room description...",
                            FloorId = 5,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 300f,
                            X = 700f,
                            Y = 260f
                        },
                        new
                        {
                            Id = 33,
                            Description = "Room description...",
                            FloorId = 5,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 270f,
                            X = 50f,
                            Y = 30f
                        },
                        new
                        {
                            Id = 34,
                            Description = "Room description...",
                            FloorId = 5,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 280f,
                            X = 720f,
                            Y = 30f
                        },
                        new
                        {
                            Id = 35,
                            Description = "Room description...",
                            FloorId = 5,
                            Height = 90f,
                            Name = "WC",
                            Type = 2,
                            Width = 150f,
                            X = 50f,
                            Y = 170f
                        },
                        new
                        {
                            Id = 36,
                            Description = "Room description...",
                            FloorId = 6,
                            Height = 140f,
                            Name = "Operation room",
                            Type = 1,
                            Width = 400f,
                            X = 320f,
                            Y = 30f
                        },
                        new
                        {
                            Id = 37,
                            Description = "Room description...",
                            FloorId = 6,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 380f,
                            X = 320f,
                            Y = 260f
                        },
                        new
                        {
                            Id = 38,
                            Description = "Room description...",
                            FloorId = 6,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 270f,
                            X = 50f,
                            Y = 260f
                        },
                        new
                        {
                            Id = 39,
                            Description = "Room description...",
                            FloorId = 6,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 300f,
                            X = 700f,
                            Y = 260f
                        },
                        new
                        {
                            Id = 40,
                            Description = "Room description...",
                            FloorId = 6,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 270f,
                            X = 50f,
                            Y = 30f
                        },
                        new
                        {
                            Id = 41,
                            Description = "Room description...",
                            FloorId = 6,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 280f,
                            X = 720f,
                            Y = 30f
                        },
                        new
                        {
                            Id = 42,
                            Description = "Room description...",
                            FloorId = 6,
                            Height = 90f,
                            Name = "WC",
                            Type = 2,
                            Width = 150f,
                            X = 50f,
                            Y = 170f
                        },
                        new
                        {
                            Id = 43,
                            Description = "Room description...",
                            FloorId = 7,
                            Height = 140f,
                            Name = "Operation room",
                            Type = 1,
                            Width = 400f,
                            X = 320f,
                            Y = 30f
                        },
                        new
                        {
                            Id = 44,
                            Description = "Room description...",
                            FloorId = 7,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 380f,
                            X = 320f,
                            Y = 260f
                        },
                        new
                        {
                            Id = 45,
                            Description = "Room description...",
                            FloorId = 7,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 270f,
                            X = 50f,
                            Y = 260f
                        },
                        new
                        {
                            Id = 46,
                            Description = "Room description...",
                            FloorId = 7,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 300f,
                            X = 700f,
                            Y = 260f
                        },
                        new
                        {
                            Id = 47,
                            Description = "Room description...",
                            FloorId = 7,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 270f,
                            X = 50f,
                            Y = 30f
                        },
                        new
                        {
                            Id = 48,
                            Description = "Room description...",
                            FloorId = 7,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 280f,
                            X = 720f,
                            Y = 30f
                        },
                        new
                        {
                            Id = 49,
                            Description = "Room description...",
                            FloorId = 7,
                            Height = 90f,
                            Name = "WC",
                            Type = 2,
                            Width = 150f,
                            X = 50f,
                            Y = 170f
                        },
                        new
                        {
                            Id = 50,
                            Description = "Room description...",
                            FloorId = 8,
                            Height = 140f,
                            Name = "Operation room",
                            Type = 1,
                            Width = 400f,
                            X = 320f,
                            Y = 30f
                        },
                        new
                        {
                            Id = 51,
                            Description = "Room description...",
                            FloorId = 8,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 380f,
                            X = 320f,
                            Y = 260f
                        },
                        new
                        {
                            Id = 52,
                            Description = "Room description...",
                            FloorId = 8,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 270f,
                            X = 50f,
                            Y = 260f
                        },
                        new
                        {
                            Id = 53,
                            Description = "Room description...",
                            FloorId = 8,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 300f,
                            X = 700f,
                            Y = 260f
                        },
                        new
                        {
                            Id = 54,
                            Description = "Room description...",
                            FloorId = 8,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 270f,
                            X = 50f,
                            Y = 30f
                        },
                        new
                        {
                            Id = 55,
                            Description = "Room description...",
                            FloorId = 8,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 280f,
                            X = 720f,
                            Y = 30f
                        },
                        new
                        {
                            Id = 56,
                            Description = "Room description...",
                            FloorId = 8,
                            Height = 90f,
                            Name = "WC",
                            Type = 2,
                            Width = 150f,
                            X = 50f,
                            Y = 170f
                        },
                        new
                        {
                            Id = 57,
                            Description = "Room description...",
                            FloorId = 9,
                            Height = 140f,
                            Name = "Operation room",
                            Type = 1,
                            Width = 400f,
                            X = 320f,
                            Y = 30f
                        },
                        new
                        {
                            Id = 58,
                            Description = "Room description...",
                            FloorId = 9,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 380f,
                            X = 320f,
                            Y = 260f
                        },
                        new
                        {
                            Id = 59,
                            Description = "Room description...",
                            FloorId = 9,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 270f,
                            X = 50f,
                            Y = 260f
                        },
                        new
                        {
                            Id = 60,
                            Description = "Room description...",
                            FloorId = 9,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 300f,
                            X = 700f,
                            Y = 260f
                        },
                        new
                        {
                            Id = 61,
                            Description = "Room description...",
                            FloorId = 9,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 270f,
                            X = 50f,
                            Y = 30f
                        },
                        new
                        {
                            Id = 62,
                            Description = "Room description...",
                            FloorId = 9,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 280f,
                            X = 720f,
                            Y = 30f
                        },
                        new
                        {
                            Id = 63,
                            Description = "Room description...",
                            FloorId = 9,
                            Height = 90f,
                            Name = "WC",
                            Type = 2,
                            Width = 150f,
                            X = 50f,
                            Y = 170f
                        },
                        new
                        {
                            Id = 64,
                            Description = "Room description...",
                            FloorId = 10,
                            Height = 140f,
                            Name = "Operation room",
                            Type = 1,
                            Width = 400f,
                            X = 320f,
                            Y = 30f
                        },
                        new
                        {
                            Id = 65,
                            Description = "Room description...",
                            FloorId = 10,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 380f,
                            X = 320f,
                            Y = 260f
                        },
                        new
                        {
                            Id = 66,
                            Description = "Room description...",
                            FloorId = 10,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 270f,
                            X = 50f,
                            Y = 260f
                        },
                        new
                        {
                            Id = 67,
                            Description = "Room description...",
                            FloorId = 10,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 300f,
                            X = 700f,
                            Y = 260f
                        },
                        new
                        {
                            Id = 68,
                            Description = "Room description...",
                            FloorId = 10,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 270f,
                            X = 50f,
                            Y = 30f
                        },
                        new
                        {
                            Id = 69,
                            Description = "Room description...",
                            FloorId = 10,
                            Height = 140f,
                            Name = "Room for appointments",
                            Type = 0,
                            Width = 280f,
                            X = 720f,
                            Y = 30f
                        },
                        new
                        {
                            Id = 70,
                            Description = "Room description...",
                            FloorId = 10,
                            Height = 90f,
                            Name = "WC",
                            Type = 2,
                            Width = 150f,
                            X = 50f,
                            Y = 170f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
