// <auto-generated />
using System;
using Hospital.Mapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Hospital.Migrations
{
    [DbContext(typeof(HospitalDbContext))]
    [Migration("20211105114309_firstMigration")]
    partial class firstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("ClinicCore.Model.FeedbackMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("CanBePublished")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Identity")
                        .HasColumnType("text");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FeedbackMessages");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CanBePublished = true,
                            Date = new DateTime(2021, 4, 29, 18, 34, 21, 0, DateTimeKind.Unspecified),
                            Identity = "acaNikolic",
                            IsAnonymous = false,
                            IsPublished = false,
                            Text = "Zadovoljan sam uslugom."
                        },
                        new
                        {
                            Id = 2L,
                            CanBePublished = true,
                            Date = new DateTime(2021, 6, 21, 14, 21, 56, 0, DateTimeKind.Unspecified),
                            Identity = "NikolaTodorovic94",
                            IsAnonymous = true,
                            IsPublished = false,
                            Text = "Čekanje je moglo biti kraće."
                        },
                        new
                        {
                            Id = 3L,
                            CanBePublished = false,
                            Date = new DateTime(2021, 2, 16, 11, 8, 47, 0, DateTimeKind.Unspecified),
                            Identity = "MarijaPopovic",
                            IsAnonymous = false,
                            IsPublished = false,
                            Text = "Informacionom sistemu potrebne su određene popravke."
                        },
                        new
                        {
                            Id = 4L,
                            CanBePublished = true,
                            Date = new DateTime(2021, 5, 20, 9, 10, 21, 0, DateTimeKind.Unspecified),
                            Identity = "UrosDevic0",
                            IsAnonymous = false,
                            IsPublished = false,
                            Text = "Odlični lekari."
                        },
                        new
                        {
                            Id = 5L,
                            CanBePublished = true,
                            Date = new DateTime(2021, 9, 30, 7, 50, 19, 0, DateTimeKind.Unspecified),
                            Identity = "MladenAlicic1",
                            IsAnonymous = false,
                            IsPublished = true,
                            Text = "Savremena bolnica koju bih preporučio ljudima."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
