version: '3.8' 

services:
  patient-front:
    #image: nenadbecanovic/patient-gateway:latest
    image: patient
    build:
      dockerfile: ../../stacks/build/patient-gateway/Dockerfile
      context: ../../
    depends_on:
      - "hospital-api"
    ports:
      - "3200:3200"
    networks: 
      - application

  manager-front:
    image: nenadbecanovic/manager-gateway:latest
    depends_on:
      - "hospital-api"
    ports:
      - "4200:4200"
    networks: 
      - application  
      

  integration-api:
    image: nenadbecanovic/integration-api:latest
    depends_on:
      - "database"
    ports:
      - "52844:80"     
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_SCHEMA: hospitalDb
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
    networks:
      - application
      - database
  
  database: 
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - type: volume
        source: integration-data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./database.sql 
        target: /docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "integrationDb"
    networks:
      - database
volumes:
  integration-data:

networks:
  application:
    name: application
    driver: bridge
  database:
    driver: bridge