version: '3.2' 

services:
  patient-front:
    image: nenadbecanovic/patient-gateway:latest
    depends_on:
      - "integration-api"
    ports:
      - "3200:3200"
    networks: 
      - application

  manager-front:
    image: nenadbecanovic/manager-gateway:latest
    depends_on:
      - "integration-api"
    ports:
      - "4200:4200"
    networks: 
      - application  
      

  integration-api:
    image: nenadbecanovic/integration-api:latest
    depends_on:
      - "database"
      - "rabbitmq3"
    ports:
      - "52844:80"     
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5433
      DATABASE_SCHEMA: integrationDb
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
    networks:
      - application
      - database
  
  database: 
    image: postgres:latest
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - type: volume
        source: integration-data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./database.sql 
        target: /docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "integrationDb"
    networks:
      - database

  rabbitmq3:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: 'secret cookie here'
    volumes:
      - integration-data:/var/lib/rabbitmq
    ports:
      - 15672:15672
volumes:
  integration-data:

networks:
  application:
    driver: bridge
  database:
    driver: bridge