version: '3.2' 

services:

  proxy:
    build: 
      context: ./Proxy
      dockerfile: Dockerfile
    ports: 
      - "80:80"
    restart: always
    networks:
      - hospitalapi_application

  manager-front:
    #image: nenadbecanovic/manager-gateway:latest
    image: manager
    build:
      context: ../../
      dockerfile: stacks/build/manager-gateway/Dockerfile
    ports:
      - "4200:80"
    networks: 
      - hospitalapi_application

  integration-api:
    #image: nenadbecanovic/integration-api:latest
    image: integrationapi
    build:
      context: ../
      dockerfile: ../stacks/build/integration/Dockerfile
    depends_on:
      - "database"
      - "rabbitmq3"
    ports:
      - "5001:80"     
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_SCHEMA: integrationDb
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password
    networks:
      - hospitalapi_application
      - database
  
  database: 
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - type: volume
        source: integration-data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./database.sql 
        target: /docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "integrationDb"
    networks:
      - database

  rabbitmq3:
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: 'secret cookie here'
    volumes:
      - integration-data:/var/lib/rabbitmq
    ports:
      - 15672:15672
volumes:
  integration-data:

networks:
  hospitalapi_application:
    external: true
  database:
    driver: bridge