

CREATE TABLE public."ApiKeys" (
    "Id" integer NOT NULL,
    "Name" text,
    "Key" text,
    "BaseUrl" text,
    "Category" text,
    "City" text,
    "ImagePath" text,
    "Note" text
);


ALTER TABLE public."ApiKeys" OWNER TO postgres;

--
-- TOC entry 210 (class 1259 OID 43870)
-- Name: ApiKeys_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."ApiKeys" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ApiKeys_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 43905)
-- Name: FeedbackReplies; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."FeedbackReplies" (
    "Id" integer NOT NULL,
    "Text" text,
    "SenderId" integer NOT NULL,
    "ReceiverId" integer NOT NULL,
    "TimeOfSending" timestamp without time zone NOT NULL,
    "FeedbackId" integer NOT NULL
);


ALTER TABLE public."FeedbackReplies" OWNER TO postgres;

--
-- TOC entry 214 (class 1259 OID 43904)
-- Name: FeedbackReplies_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."FeedbackReplies" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."FeedbackReplies_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 43913)
-- Name: Feedbacks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Feedbacks" (
    "Id" integer NOT NULL,
    "Text" text,
    "SenderId" integer NOT NULL,
    "ReceiverId" integer NOT NULL,
    "TimeOfSending" timestamp without time zone NOT NULL
);


ALTER TABLE public."Feedbacks" OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 43912)
-- Name: Feedbacks_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Feedbacks" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Feedbacks_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 43921)
-- Name: MedicationConsumption; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."MedicationConsumption" (
    "Id" integer NOT NULL,
    "Name" text,
    "Amount" integer NOT NULL,
    "Date" timestamp without time zone NOT NULL
);


ALTER TABLE public."MedicationConsumption" OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 43920)
-- Name: MedicationConsumptions_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."MedicationConsumption" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."MedicationConsumptions_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 43937)
-- Name: Medicines; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Medicines" (
    "Id" integer NOT NULL,
    "Name" text,
    "Quantity" integer NOT NULL,
    "Manufacturer" text,
    "Usage" text,
    "Weight" integer NOT NULL,
    "SideEffects" text[],
    "Reactions" text[],
    "CompatibileMedicine" integer[]
);


ALTER TABLE public."Medicines" OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 43936)
-- Name: Medicines_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Medicines" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Medicines_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 213 (class 1259 OID 43879)
-- Name: Messages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Messages" (
    "Id" integer NOT NULL,
    "Sender" text,
    "MessageText" text,
    "Receiver" text
);


ALTER TABLE public."Messages" OWNER TO postgres;

--
-- TOC entry 212 (class 1259 OID 43878)
-- Name: Messages_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Messages" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Messages_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 43947)
-- Name: Notification; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Notification" (
    "Id" integer NOT NULL,
    "Title" text,
    "Content" text,
    "Date" timestamp without time zone NOT NULL,
    "Seen" boolean NOT NULL
);


ALTER TABLE public."Notification" OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 43946)
-- Name: Notification_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Notification" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Notification_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 43929)
-- Name: PharmacyPromotions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PharmacyPromotions" (
    "Id" integer NOT NULL,
    "Title" text,
    "Content" text,
    "StartTime" timestamp without time zone NOT NULL,
    "EndTime" timestamp without time zone NOT NULL,
    "Posted" boolean NOT NULL,
    "PharmacyName" text
);


ALTER TABLE public."PharmacyPromotions" OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 43928)
-- Name: PharmacyPromotions_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."PharmacyPromotions" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PharmacyPromotions_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 209 (class 1259 OID 43865)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 3206 (class 2606 OID 43897)
-- Name: ApiKeys PK_ApiKeys; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ApiKeys"
    ADD CONSTRAINT "PK_ApiKeys" PRIMARY KEY ("Id");


--
-- TOC entry 3210 (class 2606 OID 43911)
-- Name: FeedbackReplies PK_FeedbackReplies; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."FeedbackReplies"
    ADD CONSTRAINT "PK_FeedbackReplies" PRIMARY KEY ("Id");


--
-- TOC entry 3212 (class 2606 OID 43919)
-- Name: Feedbacks PK_Feedbacks; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Feedbacks"
    ADD CONSTRAINT "PK_Feedbacks" PRIMARY KEY ("Id");


--
-- TOC entry 3214 (class 2606 OID 43945)
-- Name: MedicationConsumption PK_MedicationConsumption; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MedicationConsumption"
    ADD CONSTRAINT "PK_MedicationConsumption" PRIMARY KEY ("Id");


--
-- TOC entry 3218 (class 2606 OID 43943)
-- Name: Medicines PK_Medicines; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Medicines"
    ADD CONSTRAINT "PK_Medicines" PRIMARY KEY ("Id");


--
-- TOC entry 3208 (class 2606 OID 43888)
-- Name: Messages PK_Messages; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Messages"
    ADD CONSTRAINT "PK_Messages" PRIMARY KEY ("Id");


--
-- TOC entry 3220 (class 2606 OID 43953)
-- Name: Notification PK_Notification; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Notification"
    ADD CONSTRAINT "PK_Notification" PRIMARY KEY ("Id");


--
-- TOC entry 3216 (class 2606 OID 43935)
-- Name: PharmacyPromotions PK_PharmacyPromotions; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PharmacyPromotions"
    ADD CONSTRAINT "PK_PharmacyPromotions" PRIMARY KEY ("Id");


--
-- TOC entry 3204 (class 2606 OID 43869)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


-- Completed on 2022-01-10 20:24:52

--
-- PostgreSQL database dump complete
--

INSERT INTO public."MedicationConsumption" ("Id", "Name", "Amount", "Date") VALUES (1, 'Brufen', 30, '2021-11-10 00:00:00');
INSERT INTO public."MedicationConsumption" ("Id", "Name", "Amount", "Date") VALUES (2, 'Brufen', 25, '2021-11-12 00:00:00');
INSERT INTO public."MedicationConsumption" ("Id", "Name", "Amount", "Date") VALUES (3, 'Panadol', 40, '2021-11-10 00:00:00');
INSERT INTO public."MedicationConsumption" ("Id", "Name", "Amount", "Date") VALUES (4, 'Paracetamol', 33, '2021-11-05 00:00:00');
INSERT INTO public."MedicationConsumption" ("Id", "Name", "Amount", "Date") VALUES (5, 'Robenan', 15, '2021-11-09 00:00:00');
INSERT INTO public."MedicationConsumption" ("Id", "Name", "Amount", "Date") VALUES (6, 'Andol', 10, '2021-11-13 00:00:00');


--
-- TOC entry 3374 (class 0 OID 43937)
-- Dependencies: 223
-- Data for Name: Medicines; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3364 (class 0 OID 43879)
-- Dependencies: 213
-- Data for Name: Messages; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3376 (class 0 OID 43947)
-- Dependencies: 225
-- Data for Name: Notification; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3372 (class 0 OID 43929)
-- Dependencies: 221
-- Data for Name: PharmacyPromotions; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3360 (class 0 OID 43865)
-- Dependencies: 209
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") VALUES ('20211103170303_FirstMigration', '5.0.11');
INSERT INTO public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") VALUES ('20211103232945_SecondMigration', '5.0.11');
INSERT INTO public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") VALUES ('20211104000310_ThirdMigration', '5.0.11');
INSERT INTO public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") VALUES ('20211104000824_FourthMigration', '5.0.11');
INSERT INTO public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") VALUES ('20211104001202_FifthMigration', '5.0.11');
INSERT INTO public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") VALUES ('20211104212418_SixthMigration', '5.0.11');
INSERT INTO public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") VALUES ('20211105162453_SeventhMigration', '5.0.11');
INSERT INTO public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") VALUES ('20211119153824_add-city-to-apikey', '5.0.11');
INSERT INTO public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") VALUES ('20211121144932_EighthMigration', '5.0.11');
INSERT INTO public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") VALUES ('20211122155539_EightMigration', '5.0.11');
INSERT INTO public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") VALUES ('20211123191707_medicine0', '5.0.11');
INSERT INTO public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") VALUES ('20211208151922_AddNotificationMigration', '5.0.11');
INSERT INTO public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") VALUES ('20211208181908_AddPublicNotificationMigration', '5.0.11');
INSERT INTO public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") VALUES ('20211208183145_AddNotificationMigration2', '5.0.11');
INSERT INTO public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") VALUES ('20211209014516_ApiKeyExpended', '5.0.11');


--
-- TOC entry 3382 (class 0 OID 0)
-- Dependencies: 210
-- Name: ApiKeys_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."ApiKeys_Id_seq"', 1, false);


--
-- TOC entry 3383 (class 0 OID 0)
-- Dependencies: 214
-- Name: FeedbackReplies_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."FeedbackReplies_Id_seq"', 1, false);


--
-- TOC entry 3384 (class 0 OID 0)
-- Dependencies: 216
-- Name: Feedbacks_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Feedbacks_Id_seq"', 1, false);


--
-- TOC entry 3385 (class 0 OID 0)
-- Dependencies: 218
-- Name: MedicationConsumptions_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."MedicationConsumptions_Id_seq"', 7, false);


--
-- TOC entry 3386 (class 0 OID 0)
-- Dependencies: 222
-- Name: Medicines_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Medicines_Id_seq"', 1, false);


--
-- TOC entry 3387 (class 0 OID 0)
-- Dependencies: 212
-- Name: Messages_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Messages_Id_seq"', 1, false);


--
-- TOC entry 3388 (class 0 OID 0)
-- Dependencies: 224
-- Name: Notification_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Notification_Id_seq"', 1, false);


--
-- TOC entry 3389 (class 0 OID 0)
-- Dependencies: 220
-- Name: PharmacyPromotions_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."PharmacyPromotions_Id_seq"', 1, false);


-- Completed on 2022-01-10 20:27:19

--
-- PostgreSQL database dump complete
--


