CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "ApiKeys" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "Key" text NULL,
    "BaseUrl" text NULL,
    CONSTRAINT "PK_ApiKeys" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211103170303_FirstMigration', '5.0.11');

COMMIT;

START TRANSACTION;

CREATE TABLE "Messages" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Sender" text NULL,
    "MessageText" text NULL,
    "Receiver" text NULL,
    CONSTRAINT "PK_Messages" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211103232945_SecondMigration', '5.0.11');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211104000310_ThirdMigration', '5.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "Messages" ALTER COLUMN "Id" TYPE integer;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211104000824_FourthMigration', '5.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "ApiKeys" ALTER COLUMN "Id" TYPE integer;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211104001202_FifthMigration', '5.0.11');

COMMIT;

START TRANSACTION;

CREATE TABLE "FeedbackReplies" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Text" text NULL,
    "SenderId" integer NOT NULL,
    "ReceiverId" integer NOT NULL,
    "TimeOfSending" timestamp without time zone NOT NULL,
    "FeedbackId" integer NOT NULL,
    CONSTRAINT "PK_FeedbackReplies" PRIMARY KEY ("Id")
);

CREATE TABLE "Feedbacks" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Text" text NULL,
    "SenderId" integer NOT NULL,
    "ReceiverId" integer NOT NULL,
    "TimeOfSending" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_Feedbacks" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211104212418_SixthMigration', '5.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "ApiKeys" ADD "Category" text NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211105162453_SeventhMigration', '5.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "ApiKeys" ADD "City" text NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211119153824_add-city-to-apikey', '5.0.11');

COMMIT;

START TRANSACTION;

CREATE TABLE "MedicationConsumptions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "Amount" integer NOT NULL,
    "Date" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_MedicationConsumptions" PRIMARY KEY ("Id")
);

INSERT INTO "MedicationConsumptions" ("Id", "Amount", "Date", "Name")
VALUES (1, 30, TIMESTAMP '2021-11-10 00:00:00', 'Brufen');
INSERT INTO "MedicationConsumptions" ("Id", "Amount", "Date", "Name")
VALUES (2, 25, TIMESTAMP '2021-11-12 00:00:00', 'Brufen');
INSERT INTO "MedicationConsumptions" ("Id", "Amount", "Date", "Name")
VALUES (3, 40, TIMESTAMP '2021-11-10 00:00:00', 'Panadol');
INSERT INTO "MedicationConsumptions" ("Id", "Amount", "Date", "Name")
VALUES (4, 33, TIMESTAMP '2021-11-05 00:00:00', 'Paracetamol');
INSERT INTO "MedicationConsumptions" ("Id", "Amount", "Date", "Name")
VALUES (5, 15, TIMESTAMP '2021-11-09 00:00:00', 'Robenan');
INSERT INTO "MedicationConsumptions" ("Id", "Amount", "Date", "Name")
VALUES (6, 10, TIMESTAMP '2021-11-13 00:00:00', 'Andol');

SELECT setval(
    pg_get_serial_sequence('"MedicationConsumptions"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "MedicationConsumptions") + 1,
        nextval(pg_get_serial_sequence('"MedicationConsumptions"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211121144932_EighthMigration', '5.0.11');

COMMIT;

START TRANSACTION;

CREATE TABLE "PharmacyPromotions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NULL,
    "Content" text NULL,
    "StartTime" timestamp without time zone NOT NULL,
    "EndTime" timestamp without time zone NOT NULL,
    "Posted" boolean NOT NULL,
    "PharmacyName" text NULL,
    CONSTRAINT "PK_PharmacyPromotions" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211122155539_EightMigration', '5.0.11');

COMMIT;

START TRANSACTION;

CREATE TABLE "Medicines" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "Quantity" integer NOT NULL,
    "Manufacturer" text NULL,
    "Usage" text NULL,
    "Weight" integer NOT NULL,
    "SideEffects" text[] NULL,
    "Reactions" text[] NULL,
    "CompatibileMedicine" integer[] NULL,
    CONSTRAINT "PK_Medicines" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211123191707_medicine0', '5.0.11');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211208151922_AddNotificationMigration', '5.0.11');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211208181908_AddPublicNotificationMigration', '5.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "MedicationConsumptions" DROP CONSTRAINT "PK_MedicationConsumptions";

ALTER TABLE "MedicationConsumptions" RENAME TO "MedicationConsumption";

ALTER TABLE "MedicationConsumption" ADD CONSTRAINT "PK_MedicationConsumption" PRIMARY KEY ("Id");

CREATE TABLE "Notification" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NULL,
    "Content" text NULL,
    "Date" timestamp without time zone NOT NULL,
    "Seen" boolean NOT NULL,
    CONSTRAINT "PK_Notification" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211208183145_AddNotificationMigration2', '5.0.11');

COMMIT;

START TRANSACTION;

ALTER TABLE "ApiKeys" ADD "ImagePath" text NULL;

ALTER TABLE "ApiKeys" ADD "Note" text NULL;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211209014516_ApiKeyExpended', '5.0.11');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220111061855_first', '5.0.11');

COMMIT;

