version: '3.2'
services:
  postgres-database:
    image: postgres 
    restart: always
    networks: 
      - pharmacy-database 
    environment:
      POSTGRES_PASSWORD: /run/secrets/db-password
      POSTGRES_USER: /run/secrets/db-user
      POSTGRES_DB: pharmacyDb
    secrets:
      - db-password
      - db-user
    volumes:
      - type: volume
        source: database-data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./database.sql
        target: /docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"

  pharmacy:
    image: nenadbecanovic/pharmacy-api:latest
    #image: pharmacyapi
    #build:
    #  context: ../
    #  dockerfile: stacks/build/pharmacy/Dockerfile
    depends_on:
      - postgres-database
    environment: 
      DATABASE_HOST: postgres-database
      DATABASE_PORT: 5432
      DATABASE_SCHEMA: pharmacyDb
      DATABASE_PASSWORD: /run/secrets/db-password
      DATABASE_USER: /run/secrets/db-user
      RABBITMQ_HOST: rabbitmq
    secrets:
      - db-password
      - db-user
    ports:
      - "5002:80" 
    restart: on-failure
    networks:
      - hospitalapi_application
      - pharmacy-database
      - integrationapi_rabbit

volumes:
  database-data:

networks:
  hospitalapi_application:
    external: true
  integrationapi_rabbit:
    external: true
  pharmacy-database:
    driver: bridge

secrets:
  db-password:
   external: database_password
  db-user:
   external: database_user
