version: '3.2'
services:
  postgres-database:
    image: postgres 
    restart: always
    networks: 
      - pharmacy-database 
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: pharmacyDb
    volumes:
      - type: volume
        source: database-data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./database.sql
        target: /docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"

  pharmacy:
    #image: nenadbecanovic/pharmacy-api:latest
    image: pharmacyapi
    build:
      context: ../
      dockerfile: stacks/build/pharmacy/Dockerfile
    depends_on:
      - postgres-database
      - rabbitmq3
    environment: 
      DATABASE_HOST: postgres-database
      DATABASE_PORT: 5432
      DATABASE_SCHEMA: pharmacyDb
      DATABASE_PASSWORD: password
      DATABASE_USER: postgres
    ports:
      - "5002:80" 
    restart: on-failure
    networks:
      - hospitalapi_application
      - pharmacy-database

  rabbitmq3:
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: 'secret cookie here'
    volumes:
      - database-data:/var/lib/rabbitmq
    ports:
      - 5672:5672
volumes:
  database-data:

networks:
  hospitalapi_application:
    external: true
  pharmacy-database:
    driver: bridge