version: '3.2'
services:
  postgres-database:
    image: postgres 
    restart: always
    networks: 
      - pharmacy-database 
    environment:
      POSTGRES_PASSWORD: /run/secrets/database_password
      POSTGRES_USER: /run/secrets/database_user
      POSTGRES_DB: pharmacyDb
    secrets:
      - database_password
      - database_user
    volumes:
      - type: volume
        source: database-data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./database.sql
        target: /docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"

  pharmacy:
    image: nenadbecanovic/pharmacy-api:latest
    #image: pharmacyapi
    #build:
    #  context: ../
    #  dockerfile: stacks/build/pharmacy/Dockerfile
    depends_on:
      - postgres-database
    environment: 
      DATABASE_HOST: postgres-database
      DATABASE_PORT: 5432
      DATABASE_SCHEMA: pharmacyDb
      DATABASE_PASSWORD: /run/secrets/database_password
      DATABASE_USER: /run/secrets/database_user
      RABBITMQ_HOST: rabbitmq
    secrets:
      - database_password
      - database_user
    ports:
      - "5002:80" 
    restart: on-failure
    networks:
      - hospital_application
      - pharmacy-database

volumes:
  database-data:

networks:
  hospital_application:
    external: true
  pharmacy-database:
    driver: bridge

secrets:
  database_password:
   external: true
  database_user:
   external: true
