version: '3.2' 

services:

  proxy:
    build: 
      context: ./Proxy
      dockerfile: Dockerfile
    ports: 
      - "8081:8080"
    restart: always
    networks:
      - application
        
  patient-front:
    image: nenadbecanovic/patient-gateway:latest
    #image: patient
    #build:
    #  context: ../../
    #  dockerfile: stacks/build/patient-gateway/Dockerfile
    depends_on:
      - "hospital-api"
    ports:
      - "3200:8080"
    networks: 
      - application

  hospital-api:
    image: nenadbecanovic/hospital-api:latest
    #image: hospitalapi
    #build:
    #  context: ../
    #  dockerfile: ../stacks/build/hospital/Dockerfile
    depends_on:
      - "database"
    ports:
      - "5000:8080"
    secrets:
      - database_password
      - database_user
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_SCHEMA: hospitalDb
      DATABASE_USER: /run/secrets/database_user
      DATABASE_PASSWORD: /run/secrets/database_password
    networks:
      - application
      - hospital-database
  
  database: 
    image: postgres:latest
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - type: volume
        source: hospital-data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./database.sql 
        target: /docker-entrypoint-initdb.d/init.sql
    secrets:
      - database_password
      - database_user
    environment:
      POSTGRES_USER: /run/secrets/database_user
      POSTGRES_PASSWORD: /run/secrets/database_password
      POSTGRES_DB: "hospitalDb"
    networks:
      - hospital-database
volumes:
  hospital-data:

networks:
  application:
    external: true
  hospital-database:
    external: true

secrets:
  database_password:
   external: true
  database_user:
   external: true