name: Hospital Integration Tests

on:
  pull_request:
    branches: [ develop]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Execute tests 
        run: docker-compose -f docker-compose-hospital-tests.yml up --exit-code-from hospital-integration-tests hospital-integration-tests