on:
  push:
    branches:
    - main
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
env:
  HOSPITAL-DLL-PATH : 'HealthCareClinic/Hospital/Hospital.csproj'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Build
      run: dotnet build ${{ env.HOSPITAL-DLL-PATH }} --configuration Release /p:Version=${VERSION}
    - name: Test
      run: dotnet test ${{ env.HOSPITAL-DLL-PATH }} --configuration Release /p:Version=${VERSION} --no-build
    - name: Pack
      run: dotnet pack  ${{ env.HOSPITAL-DLL-PATH }} --configuration Release /p:Version=${VERSION} --no-build --output .
    - name: Push
      run: dotnet nuget push HOSPITAL.IS.${VERSION}.nupkg --source https://nuget.pkg.github.com/Health-Care-Clinic/index.json --api-key ${GITHUB_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.PACKAGE_TOKEN }}