name: Pharmacy Integration Tests

on:
  push:
    branches: [ feat(d)/integration-testing]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Execute tests 
        run: docker-compose up --file docker-compose-pharmacy-tests.yml --exit-code-from pharmacy-integration-tests pharmacy-integration-tests