name: Deploy To Server
on:
  push:
   branches: [ feat(d)/deploy-to-server ]

jobs:
  deploy:
   name: Deploy
   runs-on: ubuntu-latest
   steps:
    - name: Testing server ssh connection
      uses: appleboy/ssh-action@master
      with:
       host: 79.101.34.218 
       username: student
       key: ${{ secrets.STUDENT_KEY}}
       port: 22210
       script: |
         cd Health-Care-Clinic
         git checkout master
         git pull origin develop
         git status
         cd "HealthCareClinic/Hospital API"
